
name: 'shopify'
version: '1.0.0'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models: 
  shopify:
    materialized: table
    intermediate:
      materialized: table

vars:
  shopify:
    shopify_customer: "{{ ref('stg_shopify__customer') }}"
    shopify_order: "{{ ref('stg_shopify__order') }}"
    shopify_order_line: "{{ ref('stg_shopify__order_line') }}"
    shopify_order_line_refund: "{{ ref('stg_shopify__order_line_refund') }}"
    shopify_product: "{{ ref('stg_shopify__product') }}"